<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType></PropertyGroup><ItemGroup><ProjectReference Include="../RegIns.Core/RegIns.Core.csproj"/><ProjectReference Include="../RegIns.Host/RegIns.Host.csproj"/><PackageReference Include="Avalonia.Desktop" Version="11.3.20"/><PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.20"/></ItemGroup></Project>
